### ISSUE TITLE
Project 3 Proposal: Trace Generation

### ISSUE THREAD

**Issue by pbb59** [sampsyo/cs6120#108]
We will implement trace detection in LLVM. Instead of instrumenting the code with profiling instructions, we'll use an interpreter to do dynamic profiling on the code à la [this](https://github.com/sampsyo/llvm-ei). Our interpreter will both execute the LLVM instructions (already built-in) and generate traces dynamically from those instructions. 

First we need to modify the interpreter to allow for dynamic analysis. As instructions are streamed into the interpreter, we will add them to the current trace until we reach a control instruction. Upon reaching a control flow instruction, we will profile the branch outcome, and this instruction will not be added to the trace (or we'll add a pretend guard) . The trace will continue until we encounter back-edge.

We're going to compare the interpreter run-time of a single iteration of the loop to a single trace that we've generated.

**Team members:**
@sa2257

**Comment by sampsyo** [comment]
Sounds good overall, but TBH the `llvm-ei` approach will probably be more pain than it's worth. There are two basic problems:

- LLVM's built-in interpreter just doesn't work very well. Even when I got it to work, it ran into lots of mysterious segfaults and such, especially when making system calls (e.g., calling `printf`). I think the reason is that nobody uses it very much… everyone using LLVM for a dynamic language runtime just uses LLVM's JIT functionality to compile to native code and then runs that. Even the `lli` command, which sounds like it should be an "LLVM interpreter," actually JITs the code unless you do `-force-interpreter=true`, in which case it crashes a lot. So you may be able to get it to work for tiny programs but probably not for "real" programs.
- The hack I used in `llvm-ei` is a pretty bad idea. It can sort of work some of the time but it is guaranteed to break in mysterious ways between LLVM versions, for example. It will be at least a minor headache to get the same thing running on a modern LLVM.

I'm also not sure it's possible to extract stuff like branch resolutions directly.

For all those reasons, I think you might actually be better off with instrumenting the code… especially if you just start by profiling branch outcomes, which should allow you to completely reconstruct the execution trace.
