### ISSUE TITLE
Project 3 Proposal: Posits

### ISSUE THREAD

**Issue by Checkmate50** [sampsyo/cs6120#115]
**What will you do?**
We will implement the [Posit](https://en.wikipedia.org/wiki/Unum_(number_format)#Type_III_Unum_%E2%80%93_Posit) data type in LLVM.  Our goal is to experiment with Posit arithmetic precision compared to Floating-point precision in a realistic setting.

**How will you do it?**
We will build a custom [RTTI](https://llvm.org/docs/HowToSetUpLLVMStyleRTTI.html) for basic arithmetic Posit operations.  We will use LLVM's [small bitvectors](https://llvm.org/doxygen/classllvm_1_1SmallBitVector.html) as an underlying datatype, with operations on posits being represented simply as bitwise operations.  For simplicity, we will only implement the 32-bit Posit with 2 exponent bits.  We will implement standard [conversion algorithms](https://posithub.org/docs/Posits4.pdf) and Posit arithmetic based on existing [reference implementations].  Initially, we will only plan on implementing `padd`, `psub`, `pmult` and `pdiv`, but will consider implementing other operations if needed.

Finally, we will write a compiler to naively convert LLVM floating-point operations to LLVM posit operations through a simple surface re-write.  Since we will have only implemented `Posit32`, we will only convert values of the `Float32` datatype and the associated arithmetic operations.

**How will you empirically measure success?**
Unlike many other projects seeking to improve speed, our goal with this project is to evaluate operation _precision_.  Our tests for success will thus consist of comparing the accuracy of calculations using `Posit32` when compared with calculations using `Float32`.  For this evaluation, we will use our `F32->P32` compiler to translate LLVM programs involving floating-point operations to use `Posit32`.  We will then run both the floating-point and posit versions of the program and compare the results to a reference result.  This result can be calculated exactly by hand for small programs; for larger programs, we will instead compare these results to running the program with a much higher-precision floating point datatype (such as Double or LLVMFP128Type()).

**Team members:**
@epeguero

**Comment by sampsyo** [comment]
Sounds good overall, but let me make one very important revision to the strategy here: instead of adding a proper LLVM data type to LLVM itself, "emulate" the type by storing posits as integers.

That is, don't create a new `padd` instruction that works on a `Posit32` type that you add directly onto LLVM itself; this actually seems pretty hard to get right—and especially to generate code for. Instead, transform `fadd` instructions to _function calls_ to a `posit_add()` function that you provide as a C run-time library. Do not write the posit manipulation code yourself in LLVM; use an existing off-the-shelf posit implementation and generate code to invoke that. Store the posit values in `i32` variables.

Separately, you will run into situations where you _can't_ keep the value as a posit—for example, when calling a black-box external function with a `float` parameter. In this situation, you will want to generate calls to routines to convert back to `float` for the call.
