### ISSUE TITLE
Project 3 Proposal: Profile Guided Basic Block Reordering

### ISSUE THREAD

**Issue by Chillee** [sampsyo/cs6120#118]
**What will you do?**
Implement basic block reordering based off of profiling information.

**How will you do it?**
We will follow the basic methods outlined here in [Profile guided code positioning](https://dl.acm.org/citation.cfm?id=93550). In particular, we plan to implement section 4.2, which talks about the ordering of basic blocks.

If we have some more time, we may try to implement the additional heuristics listed here (https://arxiv.org/abs/1809.04676), which collects training data to train a ML model to combine multiple factors in more nuanced manner. Alternately, we might try to use this training data to create heuristics for non-profile based optimization.

**How will you empirically measure success?**
We will attempt to run a series of benchmarks through our pass. We should be able to use arbitrary programs, as our basic block reordering should be fairly modular and not require any special machinery. We will hope that our optimization pass provides some performance benefits on average.

**Team members:**
@q-hwang

**Comment by sampsyo** [comment]
Sounds great! One detail, though: do you know how you'll collect the profiling information? Will you use LLVM/Clang's [built-in support for profiling](https://llvm.org/docs/AdvancedBuilds.html#multi-stage-pgo) (I recommend this so you can focus on the layout tuning instead of the instrumentation)? Or were you planning on implementing an edge profiling pass yourself?
