### ISSUE TITLE
Project 4 Proposal: Static Holistic Error Locator

### ISSUE THREAD

**Issue by Neroysq** [sampsyo/cs6120#142]
**What will you do?**
I want to reproduce [SHErrLoc (Static Holistic Error Locator)](https://www.cs.cornell.edu/projects/SHErrLoc/),  a general approach to locate programmer mistakes.

**How will you do it?**
In SHErrLoc, analysis of a program contains two steps:
1. Generate constraints in SCL (SHErrLoc Constraint Language) by statically analyzing the code.

2. Build the constraint graph, and diagnose errors by applying a Bayesian model for inferring the most likely cause of program mistakes.

I plan only to implement the second part. Because it looks relatively more interesting to me, and if time permits, I'd like to investigate more on how the Bayesian interpretation correctly tells error locations.

**How will you empirically measure success?**
The paper evaluates SHErrLoc over two cases: Haskell type inference and Jif (a Java-like language with information flow control) hypothesis inference. 
I plan to follow the first case and compare the performance of my implementation to the result showed in the paper.

**Comment by sampsyo** [comment]
Cool; sounds great! Three questions, however:

- What infrastructure will you use to do this? It sounds like you are not planning to actually analyze any source code—is that correct?
- Where will you get your data from? Especially if you're going to compare with the original paper, you will need to get your hands on the same error setups.
- What metric will you use for comparison? You said "performance"—does this mean you'll compare the actual running time? That doesn't seem fair because your hardware will be newer. Is there some more objective metric you can use?
