### ISSUE TITLE
Project 4 Proposal: Dependently Typed Language

### ISSUE THREAD

**Issue by chrisroman** [sampsyo/cs6120#145]
**What will you do?**
I would like to implement a dependently typed language. I will base the language off [the Calculus of Constructions](https://www.sciencedirect.com/science/article/pii/0890540188900053). If this ends up being too simple, I will also implement user defined inductive types by following [this paper](https://www.cs.cmu.edu/~fp/papers/mfps89.pdf) which shows how to represent them in CoC. Alternatively, I can use [the Calculus of Inductive Constructions](https://hal.inria.fr/hal-01094195/document) to directly implement this dependently typed language; I am unsure which approach would prove to be simpler.

**How will you do it?**
I will be following the papers linked above to implement the type system for this dependently typed language. I will start by creating a relatively simple parser for the language, then move on to implementing the inference rules for the type system given in the papers.

**How will you empirically measure success?**
Since Coq is based off the Calculus of Constructions, I should be able to write equivalent programs in Coq and the language I create and make sure they both type check. I would like to use this language for proofs; for example that `False -> True` for some encoding of `True`, `False`, and implication.

**Team members:**
Just me

**Comment by sampsyo** [comment]
Sounds ambitious! I have one recommendation: to avoid spending time on the parser, be sure to use a parser generator library instead of hand-rolling a recursive descent parser.

I am a little less enthusiastic about your evaluation plan, which amounts to a Project 1-style "I will hand-write a handful of test cases for my implementation that it is virtually guaranteed to pass." Can you think of any way you can construct a scientific experiment that will let you objectively answer "is this implementation good?"

One way, for example, would be to find an existing library of small programs in Coq and see how many proofs you can actually check. Or another might be to measure the performance of your type checker. Please be creative, but choose something that will rigorously answer an empirical question—just concocting a test suite is not sufficient.
