### ISSUE TITLE
Project 4 Proposal: EWASM to EVM

### ISSUE THREAD

**Issue by 0x486F626F** [sampsyo/cs6120#152]
**What will you do?**
EWASM (Ethereum WebAssembly) is designed to replace EVM at Ethereum smart contract execution layer, with better performance and support for traditional programming languages, such as C/C++ and Rust. EWASM is not online yet, so it would be interesting to explore if it is possible to translate EWASM executables to EVM. Therefore, users can started developing EWASM application and run it on current EVM. When EWASM eventually replaces EVM, those application could be easily ported to new system. 

**How will you do it?**
I will look into both instruction sets to figure out if it is possible to do binary translation. 

**How will you empirically measure success?**
First I will evaluate if it is possible to fully translate EWASM to EVM. If not, what would be the restriction. 
Both instruction sets have an existing cost model, so I can compare
1. the original cost of EWASM code
2. the cost of translated EVM code from EWASH
3. the cost of EVM code if it is designed in EVM directly with the same functionality.

**Comment by sampsyo** [comment]
OK! I have one crucial question you'll need to answer before getting started: where will you get your benchmarks from? Is there a standard suite of benchmarks for either EVM or EWASM that you can use? Please try to find a collection of programs that are as representative as possible—rather than writing your own test cases by hand, which will not be very realistic.

Also, I'm curious what you mean by "both instruction sets have an existing cost model." Is this a static or dynamic cost? Are there existing tools you can use to measure it?

**Comment by 0x486F626F** [comment]
I could use benchmark from EWASM like this https://github.com/ewasm/benchmarking
For the cost models, both EWASM and EVM have defined a gas cost for each instruction, so I can evaluate how much will the EWASM program cost and how much will the translated EVM program cost. Ideally, they should have similar gas costs, but I have looked into it yet.
