### ISSUE TITLE
Project Proposal: Tracing collector for compiled bril

### ISSUE THREAD

**Issue by mdmoeller** [sampsyo/cs6120#224]
**What will you do?**

I will extend bril to support structs, then provide a compiler for this bril extension that offers automatic dynamic memory management in the form of a tracing garbage collector.

**How will you do it?**

I will first update the language definition to support structs similar to LLVM's notion of structs. The compiler I build will translate bril programs to LLVM, so I will rely on lli/clang for testing.

The garbage collector will use library calls to malloc and free, wrapped in additional book-keeping, to implement the corresponding requests for dynamic memory by bril programs. I will implement a tracing garbage collector, and, time-permitting, experiment with adding reference counting tweaks.

**How will you empirically measure success?**

Since I'm not aware of a version of this that exists, running times of compiled bril programs may not be meaningful for my compiler as a whole. Still, since I'm interested specifically in the garbage collection, there are two measurements I can take of the compiler with GC off against the compiler with GC on.

The first is that it does in fact manage memory: I will instrument the compiler to measure the memory footprint of the bril benchmark suite and report the reduction in maximum heapsize from uncollected to automatically managed programs.

The second is to measure the performance cost. I will measure the running times of the benchmark suite with manual collection against the suite using my garbage collector.

Since obviously none of the benchmark programs use my struct extension, I will need to add programs to the suite that do.

**Team members:**
Just me: @mdmoeller.

**Comment by sampsyo** [comment]
This sounds great! I think the "hard part" will be making the compiled code generate the bookkeeping necessary to navigate the roots & heap (i.e., the RTTI). Or you could go conservative, I guess.

As I mentioned elsewhere, I'd recommend starting by sprucing an existing Bril-to-LLVM compiler. There's a [standard LLVM-based compiler](https://www.cs.cornell.edu/courses/cs6120/2019fa/blog/llvm-backend-for-bril/), [one using the OCaml bindings](https://www.cs.cornell.edu/courses/cs6120/2019fa/blog/bril-to-llvm-ocaml/), and [one that generates C source code instead of LLVM IR](https://www.cs.cornell.edu/courses/cs6120/2019fa/blog/bril-c-backend/), which you can obviously then compile the rest of the way using Clang. Starting with one of these (which will need updating!) could save you a lot of time over starting from scratch.

**Comment by mdmoeller** [comment]
As asked for, my repository for this project is here: https://github.com/mdmoeller/6120_tasks/tree/master/project
