### ISSUE TITLE
Project 2 Proposal: Loop unrolling pass in LLVM

### ISSUE THREAD

**Issue by Hecmay** [sampsyo/cs6120#53]
**What will you do?**
Implement loop unrolling pass to optimize Bril program in LLVM IR representation, and map the optimized LLVM program back to Bril code. The goal is to exploit the potential of loop parallelization and generate Bril program with faster execution time.

**How will you do it?**
1. Implement `for` and `array` instruction to support loop related operations in Bril
2. Write LLVM passes to optimize the loop in LLVM IR, and map the optimized IR back to Bril program. We will set up an upper bound for the unrolling such that loops will be unrolled, partially unrolled or left unchanged depending on their sizes.

**How will you empirically measure success?**
We will develop several test cases where loops can be optimized for higher performance, including vector add and loops with data dependency. And we compare the performance of original and optimized Bril program in terms of runtime speedup. 

**Team members:**
@Hecmay @zhouyuan1119 @seanlatias

**Comment by sampsyo** [comment]
Hi, folks—this is an interesting proposal, and loop unrolling will be a good optimization. But I think there are some kinks to work out.

- Implementing a `for` instruction: I don't think you want to add new control flow constructs. Instead, the "right thing to do" is to analyze the CFG to find natural loops and optimize those. Remember that Bril is an IR, not a language that humans are supposed to write—so higher-level constructs like `for` will already be compiled down to lower-level constructs like `br` and `jmp`.
- Implementing an `array` instruction: Please reuse an existing extension that added arrays instead of creating your own. You can see them in the pull requests to the Bril repository. For example, see https://github.com/sampsyo/bril/pull/10 and https://github.com/sampsyo/bril/pull/19 and https://github.com/sampsyo/bril/pull/20.
- You have proposed to translate Bril in to LLVM, optimize it, and then translate it back to Bril. Please don't do this—instead, implement the optimization yourself directly on the Bril code. The focus on this project is on working with the IR yourself, not on learning to leverage the built-in analyses that come as part of the LLVM infrastructure. Also, LLVM already has a [loop unrolling pass](https://llvm.org/doxygen/LoopUnrollPass_8cpp_source.html), so it's not clear what your implementation would add that this existing code doesn't already do.

I also have some questions about your evaluation plan: namely, what will you measure the execution time of? The reference Bril interpreter? Some compiled version? And will this be wall-clock time or some logical counter?

Finally, I'm not entirely sure what you mean by "exploit the potential of loop parallelization." Do you intend to implement some kind of parallel execution yourself, or do you just mean you'll expose more ILP for a superscalar processor to take advantage of?

**Comment by zhouyuan1119** [comment]
Hi Adrian,

Thanks for your comment. The reason we wanted to do it in LLVM is that we wanted to evaluate the performance of the compiled code. We believe that loop unrolling will not bring us much performance benefit if we use the Bril interpreter. If we optimize in Bril, the only option would be to use the Bril-to-LLVM compiler we implemented in Project 1. Unfortunately, that compiler generates unoptimized code full of loads and stores (roughly at the same scale of -O0). We need to either implement our own passes or use existing LLVM passes to optimize that code.

**Comment by sampsyo** [comment]
You actually have several options now for compiling Bril to native code. There's also the direct ARM assembly generator and a straightforward compiler to C. There are _two_ LLVM generators—one in C++ and one in OCaml. You can use any of these to measure compiled execution speed.

> Unfortunately, that compiler generates unoptimized code full of loads and stores (roughly at the same scale of -O0).

What's the problem with this, exactly? Can't you just run the existing [mem2reg](http://llvm.org/docs/Passes.html#mem2reg-promote-memory-to-register) pass on the generated LLVM to get the higher-performing version you want?

Fundamentally, I think I'm still confused—I don't see why the need to high-performance code in the _backend_ implies that you must implement your _middle-end_ optimization in LLVM.

**Comment by zhouyuan1119** [comment]
In this case, leveraging the bril-to-C compiler implemented in #21 sounds good to me. We can do the optimization in Bril, use the work in #21 to translate the optimized code to C, use Clang or GCC to compile the C code to machine code, and then measure performance. We just want to make sure that the performance change from loop unrolling is honestly reflected in the execution time of the program. 

So I guess a modified version of our proposal would be as follows if both @Hecmay and @seanlatias agree:

**What will you do?**

We will implement a loop unrolling pass for the Bril IR. The pass will take Bril code in its JSON format, optimize it, and dump out the optimized code in JSON format. Our pass will automatically identify the loops in the input Bril code. Since loop unrolling usually shows speedup on data-parallel applications, we will also augment the Bril IR with array types so that we can have more useful and more realistic applications as our benchmarks. 

**How will you do it?**

We will modify the Bril typescript interpreter and the `bril2json` converter to add our array type. Since we are only dealing with JSON this time, we might implement our pass in either Python or C++. The pass will have a simple built-in cost model so that it can make decisions on whether to unroll the loops or not. 

**How will you empirically measure success?**

To accurately measure the effect of loop unrolling, we need to compile Bril code to native machine code since loop unrolling actually leverages the out-of-order, multi-issue features of modern processors. We will leverage the Bril-to-C compiler implemented in #21 to achieve this goal, and we will modify it so that it supports our new array type. Running the optimized code with the Bril interpreter probably won't give us any measurable speedup. We will also do that for a comparison.  

We will write some common data-parallel programs in Bril as our benchmarks, such as vector add, matrix multiplication, etc. We will also test on programs that can not be easily parallelized to more thoroughly evaluate the correctness and performance of our loop unrolling pass. 

**Team members:**
@Hecmay @zhouyuan1119 @seanlatias

**Comment by sampsyo** [comment]
Sounds good. I think the only risk with this approach is that normal compiler optimizations (in GCC or LLVM) might remove or add loop unrolling. That is, it might take your carefully unrolled loop and re-roll it, or unroll it to a different degree. So you'll need to be careful to inspect the assembly to make sure this didn't happen.

**Comment by sampsyo** [comment]
Implemented in #85.
