### ISSUE TITLE
Project 2 Proposal: Sparse Conditional Constant Propagation

### ISSUE THREAD

**Issue by anastos** [sampsyo/cs6120#54]
**What will you do?**
Implement an optimizing pass on Bril programs for sparse conditional constant propagation, as described in [Constant propagation with conditional branches](https://dl.acm.org/citation.cfm?id=103136). This pass will evaluate expressions at compile time when the inputs are determined to be constant, and find unreachable code from known constant branch conditions. These two effects of the optimization work well together as from knowledge of an untraversed control-flow path, you can discover more constant variables, and vice versa. 

**How will you do it?**
I will follow the algorithm to compute constants described in the paper, which involves converting the program to SSA form and then invoking a work-list-based data-flow analysis. The next step will be to modify the program to replace variables with their known constant values, and to remove code determined to be unreachable. Then the program needs to be converted back from SSA form. I may then need to run a pass of dead-code elimination in order to show the full effect of constant propagation.

**How will you empirically measure success?**
I will evaluate the effect on program performance by measuring the dynamic instruction counts of programs with and without the optimization applied. If I include DCE in the optimization, I will also include a version optimized by DCE alone in the comparisons in order to properly attribute where the instruction count changes are coming from.
I think that dynamic instruction count is the most fruitful statistic for evaluating Bril program performance in this case. Execution time in the interpreter would most likely see negligible differences for almost any optimization. The static instruction count would see a difference, but it does not represent program speed, and code size reduction is not the goal of this optimization. However, the effect on dynamic instruction count might not be that great either, because Bril has no support for inlined immediate values in operations, and so a `const` instruction will still be required for each constant.

**Team members:**
Just me.

**Comment by sampsyo** [comment]
Awesome! This sounds great. It's a good, solid, widely applicable optimization and will require you to also implement SSA and un-SSA passes.

It does indeed seem like a post-facto DCE will be important—especially a CFG-based DCE (i.e., pruning basic blocks that will never be exited and removing the branches that would otherwise jump to them), which is different from the value-based DCE we did in class.

I agree that dynamic instruction count is probably your best bet for a convincing measurement. I even think you might be a little to pessimistic about the potential in the face of constant instructions (i.e., no "immediates" in Bril)—the main potential will be replacing entire _groups_ of instructions with single constant instructions. On the other hand, you might consider getting a count of the _non-constant_ instructions to see if that improves any more than the raw instruction count.
