### ISSUE TITLE
Project 2 Proposal: ML based phases selection and ordering

### ISSUE THREAD

**Issue by q-hwang** [sampsyo/cs6120#70]
**What will you do?**
Implement several optimization paths and use Machine Learning to predict the best set or ordering of the paths to apply. The later one is also known as phase-ordering problem 

**How will you do it?**
Predicting a set of optimizations to apply given a fixed order of applying is closer to the real compiler setup. One example for this in the literature is [Rapidly Selecting Good Compiler Optimizations using Performance Counters.](https://www.eecis.udel.edu/~cavazos/cgo-2007.pdf) On the other hand, predicting ordering of optimizations can potentially have a larger boost in performance, e.g. [Predictive modeling methodology for compiler phase-ordering.](https://dl.acm.org/citation.cfm?doid=2872421.2872424) In general, we will collect 1)handcrafted features that encode the program and 2) objective performance metrics  that correspond to use different optimization set/order to form training and testing data. Then we will train ML models to predict this relationship.

To do this we will also need to have some infrastructure work, including implementing several common optimization and generating diverse bril programs. 

**How will you empirically measure success?**
We will benchmark against common full optimization pipelines on generated bril programs, in terms of the aimed objective, e.g. number of computations, number of tokens, actual run time when compile to llvm etc.
 
**Team members:**
@Chillee

**Comment by sampsyo** [comment]
Sounds cool! I would suggest trying to use the simplest ML primitive possible (logistic regression?), at least at first. There will be plenty of work to do just in implementing a suitable breadth of optimizations such that there is a meaningful phase ordering problem to be solved.

I also think it would be a vey good idea to plan to do a limit study—to find the worst and best ordering for a few benchmarks with an exhaustive (or otherwise very costly) search. This will help give you an idea of how the ordering you predict (cheaply, presumably) compares to the best and worst possible cases.
