### ISSUE TITLE
Project 2 Proposal: Loop Level Vectorization

### ISSUE THREAD

**Issue by liuhenry4428** [sampsyo/cs6120#71]
**What will you do?**
We will implement loop-level automatic vectorization by leveraging integer arrays and vector operations provided by the [Vector Bril](https://github.com/sampsyo/cs6120/issues/24#issue-492556245) project (and we will add more vector operations if necessary). It will entail finding looping array operations and changing them into equivalent vector operations. 

**How will you do it?**
We will first create a mechanism to identify loops with vectorizable operations (typically these will involve iterating over one or more arrays). Next, we will develop an algorithm to convert such looping operations into vector operations that behave identically. After that, we will verify that these changes work with vector interpretation from the [Integer SIMD Support](https://github.com/sampsyo/cs6120/issues/7) project.

**How will you empirically measure success?**
We will measure success by developing a series of benchmarks and then testing both the speedup of this optimization on the Bril interpreter as well as the decrease in the number of Bril instructions the interpreter executes. 

**Team members:**
Katy Voor @kavoor 
Henry Liu @liuhenry4428

**Comment by sampsyo** [comment]
Sounds like a good goal overall! I have two main comments:

- You've said that you want to vectorize array-manipulating loops, but not exactly how you'll vectorize it. When you get a chance to look, can you please specify what algorithm you'll be using to vectorize? Is there a paper you'll be using, for example?
- Rather than Vril, whose current version operates on _entire arrays_ at a time, I think you'll want to use [Phil's vector extension](https://www.cs.cornell.edu/courses/cs6120/2019fa/blog/interpreter-vector-support/), which has fixed-size vector ops. That will be more like vectorization for a real SIMD machine.

**Comment by kavoor** [comment]
We looked at the following articles for guidelines for an algorithm. We did not find a paper with a specific algorithm to implement, but instead found information on various steps of loop vectorization including finding loops, identifying dependencies, strip mining, etc.
- [LLVM's Loop Vectorizer](http://llvm.org/docs/Vectorizers.html#loops-with-unknown-trip-count)
- [Strip Mining](http://physics.ujep.cz/~zmoravec/prga/main_for/mergedProjects/optaps_for/common/optaps_vec_mine.html)
- [Data dependencies, Vectorization, Examples](http://www.cs.utexas.edu/users/pingali/CS380C/2019/lectures/david-vectorization.pdf)

**Comment by sampsyo** [comment]
Closed by #88.
